cms/urls.py
from django.conf.urls import url


from cms import views

app_name = "cms"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^center/$', views.center, name="center"),
    url(r'^camera/group/add/$', views.add_camera_group, name="add_camera_group"),
    url(r'^camera/add/$', views.add_camera, name="add_camera"),
    url(r'^file/list/$', views.file_list, name="file_list"),
    url(r'^file/upload/', views.file_upload, name="file_upload"),
    url(r'^file/concat/', views.file_concat, name="file_concat"),
    url(r'^video/playback/$', views.video_playback, name="video_playback"),
]

iV007/urls.py
# noinspection PyPackageRequirements
"""iV007 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^', include('cms.urls')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

cms/models.py
from django.db import models

# Create your models here.
from django.utils import timezone


class Organization(models.Model):
    Name = models.CharField(max_length=20, verbose_name="名称")
    Description = models.CharField(max_length=50, verbose_name="描述", null=True, blank=True)
    Status = models.IntegerField(verbose_name="状态", default=0)

    def __str__(self):
        return "{0}".format(self.Name)


class Role(models.Model):
    Name = models.CharField(max_length=20, verbose_name="名称")
    Description = models.CharField(max_length=50, verbose_name="描述", null=True, blank=True)
    Status = models.IntegerField(verbose_name="状态", default=0, blank=True)

    def __str__(self):
        return "{0}".format(self.Name)


class User(models.Model):
    Name = models.CharField(max_length=20, verbose_name="姓名")
    Password = models.CharField(max_length=30, verbose_name="密码")
    Description = models.CharField(max_length=50, verbose_name="描述", null=True, blank=True)
    RealName = models.CharField(max_length=10, verbose_name="真实姓名")
    Status = models.IntegerField(verbose_name="状态", default=0)
    Organization = models.ForeignKey(Organization, verbose_name="组织")
    Role = models.ForeignKey(Role, verbose_name="角色")
    MaxUpload = models.IntegerField(verbose_name="最大上传", default=5)
    MaxDownload = models.IntegerField(verbose_name="最大下载", default=5)

    class Meta:
        index_together = ["Name"]

    def __str__(self):
        return "{0}:{1}".format(self.Name, self.Description)


class CameraGroup(models.Model):
    Name = models.CharField(max_length=20, verbose_name="名称")
    Description = models.CharField(max_length=50, verbose_name="描述", null=True, blank=True)
    Creator = models.ForeignKey(User, verbose_name="创建人")
    CreatedTime = models.DateTimeField( verbose_name="创建时间")

    # Parent = models.ForeignKey(CameraGroup, verbose_name="父节点")

    def __str__(self):
        return "{0}".format(self.Name)


class Camera(models.Model):
    Name = models.CharField(max_length=20, verbose_name="名称")
    DeviceType = models.IntegerField(verbose_name="类型")
    Creator = models.ForeignKey(User, verbose_name="创建人")
    Group = models.ForeignKey(CameraGroup, verbose_name="分组")
    Latitude = models.FloatField(verbose_name="纬度", default=0)
    Longitude = models.FloatField(verbose_name="经度", default=0)

    # Parent = models.ForeignKey(CameraGroup, verbose_name="父节点")

    def __str__(self):
        return "{0}".format(self.Name)


class CameraTree(models.Model):
    Cameras = models.ForeignKey(Camera, verbose_name="摄像头")
    Parent = models.ForeignKey(CameraGroup, verbose_name="父节点")
    # 0：Group ,1: Camera
    ChildType = models.IntegerField(verbose_name="节点类型", default=0)

    def __str__(self):
        return "{0}".format(self.Name)

cms/views.py
import json
import os
import threading

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from cms.models import User

http_get = "GET"
http_post = "POST"
upload_folder_name = "foldername"
upload_file_name = "filename"
upload_file_infos = "fileinfos"
upload_chunk_count = "chunkcount"
upload_chunk_no = "chunkno"
upload_chunk_len = "chunklen"
upload_temp_file_format = '{0}.tmp'
upload_merge_chunk_size = 512 * 1024

error_code = "code"
error_code_succeed = 200
error_code_failed = 500

error_msg = "msg"


def index(request):
    if request.method == http_post:
        user = request.POST.get("user")
        pwd = request.POST.get("pwd")
        item = User.objects.filter(Name=user, Password=pwd)
        if item:
            return HttpResponseRedirect(reverse("cms:center"))
        else:
            return HttpResponse(json.dumps({"error": "incorrect user or pwd"}))
    else:
        return render(request, "login.html")


def get_upload_folder(folder_name):
    folder_path = os.path.join("E:\\upload", folder_name)
    return folder_path


@csrf_exempt
def file_list(request):
    if request.method == http_post:
        req_infos = json.loads(request.body)
        folder_name = req_infos[upload_folder_name]
        if folder_name:
            folder_path = get_upload_folder(folder_name)
            file_dict = get_file_list(folder_path)
            info_list = []
            for k, v in file_dict.items():
                info_list.append({upload_file_name: k, upload_chunk_len: v})

            return HttpResponse(
                json.dumps({error_code: error_code_succeed, error_msg: "succeed", upload_file_infos: info_list}))
        return HttpResponse(json.dumps({error_code: error_code_succeed, error_msg: "folder is not existed"}))


def get_file_list(folder_path):
    file_dict = {}
    if folder_path and os.path.exists(folder_path):
        files = os.listdir(folder_path)
        for f_name in files:
            f_size = os.stat(os.path.join(folder_path, f_name)).st_size
            file_dict[f_name] = f_size
    return file_dict


@csrf_exempt
def file_upload(request):
    if request.method == http_post:
        file_info = request.POST.get(upload_file_infos)
        json_file_info = json.loads(file_info)
        folder_name, chunk_no, file_len = json_file_info[upload_folder_name], json_file_info[upload_chunk_no], int(
            json_file_info[upload_chunk_len])

        src_file = request.FILES.get("file", None)

        if not folder_name or not src_file:
            return HttpResponse(json.dumps({error_code: 502, 'msg': "no files for upload!"}))

        file_name = upload_temp_file_format.format(chunk_no)

        try:
            folder_path = get_upload_folder(folder_name)
            file_dict = get_file_list(folder_path)
            exist_file_size = file_dict.get(file_name)
            if exist_file_size == file_len:
                return HttpResponse(
                    json.dumps({error_code: 200, error_msg: u" file:{0} already existed".format(file_name)}))

            if not os.path.exists(folder_path):
                os.makedirs(folder_path, exist_ok=True)
            det_file = os.path.join(folder_path, file_name)
            if os.path.exists(det_file) and os.stat(det_file).st_size == file_len:
                return HttpResponse(
                    json.dumps({error_code: 200, error_msg: u" file:{0} already existed".format(file_name)}))

            with open(det_file, 'wb+') as destFile:
                for chunk in src_file.chunks(upload_merge_chunk_size):
                    destFile.write(chunk)
            print("File upload succeed:{}".format(det_file))
            return HttpResponse(json.dumps({error_code: 200, error_msg: " upload:{0} succeed".format(file_name)}))
        except IOError:
            return HttpResponse(json.dumps({error_code: 502, error_msg: "File upload IO error:{0}".format(file_name)}))
        else:
            return HttpResponse(
                json.dumps({error_code: 502, error_msg: "File upload unknown error:{0}".format(file_name)}))
    else:
        return render(request, "FileUpload.html")


@csrf_exempt
def file_concat(request):
    if request.method == http_post:
        req_infos = json.loads(request.body)
        folder_name, file_name, file_info = req_infos[upload_folder_name], req_infos[upload_file_name], req_infos[
            upload_file_infos]
        chunk_no_list = sorted(fi[upload_chunk_no] for fi in file_info)

        folder_path = get_upload_folder(folder_name)
        is_all_concated = True

        with open(os.path.join(folder_path, file_name), 'wb+') as outfile:
            for item in chunk_no_list:
                src_file_name = upload_temp_file_format.format(item)
                try:
                    with open(os.path.join(folder_path, src_file_name), "rb") as infile:
                        outfile.write(infile.read())
                        outfile.flush()
                        print("File concat {0} -> {1} succeed".format(src_file_name, file_name))
                        is_all_concated &= True
                except IOError as err:
                    is_all_concated &= False

        if is_all_concated:
            for item in chunk_no_list:
                chunk_file = os.path.join(folder_path, upload_temp_file_format.format(item))
                try:
                    os.remove(chunk_file)
                    print("Remove chunk file {0}".format(chunk_file))
                except IOError as err:
                    print("Remove chunk file {0} failed".format(chunk_file))
        return HttpResponse(json.dumps({error_code: 200, error_msg: 'concat succeed'}))


def on_ws_message(message):
    cmd = message.content['path']
    txt = message.content['text']
    if not cmd or not txt:
        message.reply_channel.send({'text': "invalid ws url or empty text"})
        return
    req_json = json.loads(txt)
    conThread = ContactThread(req_json, message.reply_channel)
    conThread.start()
    message.reply_channel.send(
        {'text': json.dumps({'code': 200, 'msg': "start file concat {0} ".format(req_json[upload_file_name])})})


class ContactThread(threading.Thread):
    def __init__(self, txt, channel):
        threading.Thread.__init__(self)
        self.txt = txt
        self.channel = channel

    def run(self):
        print("开始线程：" + self.name)
        ws_concat_file(self.txt, self.channel)
        print("退出线程：" + self.name)


def ws_concat_file(req_json, channel):
    req_infos = req_json
    folder_name = req_infos[upload_folder_name]
    file_name = req_infos[upload_file_name]
    file_info = req_infos[upload_file_infos]
    chunk_no_list = sorted(fi[upload_chunk_no] for fi in file_info)
    folder_path = get_upload_folder(folder_name)
    is_all_concated = True
    with open(os.path.join(folder_path, file_name), 'wb+') as outfile:
        file_len = len(chunk_no_list)
        file_count = 1
        for item in chunk_no_list:
            src_file_name = upload_temp_file_format.format(item)
            try:
                with open(os.path.join(folder_path, src_file_name), "rb") as infile:
                    outfile.write(infile.read())
                    outfile.flush()
                    print("File concat {0} -> {1} succeed".format(src_file_name, file_name))
                    # channel.send({'text': {'src': src_file_name, 'dst': file_name}})
                    channel.send({'text': json.dumps({'code': 200, 'file_len': file_len, 'progress': file_count,
                                                      'filename': file_name,
                                                      'msg': "File concat {0} -> {1} succeed".format(src_file_name,
                                                                                                     file_name)})})
                    file_count += 1
                    is_all_concated &= True
            except IOError as err:
                is_all_concated &= False

    if is_all_concated:
        for item in chunk_no_list:
            chunk_file = os.path.join(folder_path, upload_temp_file_format.format(item))
            try:
                os.remove(chunk_file)
                print("Remove chunk file {0}".format(chunk_file))
            except IOError as err:
                print("Remove chunk file {0} failed".format(chunk_file))

    channel.send(
        {'text': json.dumps({'code': 200, 'filename': file_name, 'msg': "File concat {0} succeed".format(file_name)})})


def center(request):
    return render(request, "Center.html")


def add_camera_group(request):
    if request.method == http_post:
        group_name = request.POST.get("name", None)
        return HttpResponse(json.dumps({'result': "create succeed"}))
    else:
        return render(request, "AddCameraGroup.html")


def add_camera(request):
    if request.method == http_post:
        group_name = request.POST.get("name", None)
        return HttpResponse(json.dumps({'result': "create succeed"}))
    else:
        return render(request, "AddCamera.html")


def video_playback(request):
    return render(request, "videoplayer.html")

cms/templates/AddCamera.html
{% extends "base.html" %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <p><h1>添加摄像头</h1></p>
        <table>
            <tr>
                <td>名称:</td>
                <td><input id="txtName" name="name" width="50"/></td>
            </tr>
            <tr>
                <td>描述:</td>
                <td><input id="txtDes"  name="des" width="100" multiple="multiple"/></td>
            </tr>
            <tr >
                <td colspan="2"><input type="submit" content="提交" style="margin-top: 10px"/></td>
            </tr>
        </table>
    </form>

{% endblock content %}

cms/templates/AddCameraGroup.html
{% extends "base.html" %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <p><h1>添加摄像头组</h1></p>
        <table>
            <tr>
                <td>名称:</td>
                <td><input id="txtName" name="name" width="50"/></td>
            </tr>
            <tr>
                <td>描述:</td>
                <td><input id="txtDes"  name="des" width="100" multiple="multiple"/></td>
            </tr>
            <tr >
                <td colspan="2"><input type="submit" content="提交" style="margin-top: 10px"/></td>
            </tr>
        </table>
    </form>

{% endblock content %}

cms/templates/Base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>iV007</title>
    {% block header %}
        {% load static %}
        <script src="{% static "js/jquery-3.2.1.min.js" %}"></script>
         <script src="{% static "js/vue.js" %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static "css/div.css" %}"/>
    {% endblock header %}
</head>

<body>

<div id="div_top" align="top">
    {% block title %}
    {% endblock %}
</div>

<div id="div_left">
    {% block  div_left %}
    {% endblock %}
</div>

<div id="div_center">
    {% block  content %}
    {% endblock %}
</div>

<div id="div_right">
    {% block  div_right %}
    {% endblock %}
</div>
</body>
</html>

cms/templates/Center.html
{% extends "base.html" %}
{% block content %}
    <table>
        <tr>
            <td>
                <a href="{% url 'cms:add_camera_group' %}">
                       <p style="color: red"> 添加摄像头组</p>

                </a>
            </td>
        </tr>

        <tr>
            <td>
                <a href="{% url 'cms:add_camera' %}">
                    <p style="color: green"> 添加摄像头</p>
                </a>
            </td>
        </tr>
        <tr>
            <td>
                <a href="{% url 'cms:video_playback' %}">
                         <p style="color: blue">   Video player</p>

                </a>
            </td>
        </tr>

    </table>

{% endblock content %}

cms/templates/FileUpload.html
{% extends "base.html" %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>
                <td>文件名:</td>
                <td><input id="txtFilePath" name="file" type="file" width="150"/></td>
            </tr>
            <tr>
                <td colspan="2"><input type="submit" content="提交"/></td>
            </tr>
        </table>
    </form>

{% endblock content %}

cms/templates/Login.html
{% extends "base.html" %}

{% block content %}

    <script>
        socket = new WebSocket("ws://" + window.location.host + "/chat/");
        socket.onmessage = function (e) {
            alert(e.data);
        }
        socket.onopen = function () {
            socket.send("hello world");
        }
        // Call onopen directly if socket is already open
        if (socket.readyState == WebSocket.OPEN) socket.onopen();
    </script>
    <form method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td>用户名:</td>
                <td><input id="txtUser" name="user" width="50"/></td>
            </tr>
            <tr>
                <td>密码:</td>
                <td><input id="txtPwd" type="password" name="pwd" width="50"/></td>
            </tr>
            <tr>
                <td colspan="2"><input type="submit" content="提交"/></td>
            </tr>
        </table>
    </form>

    {% verbatim %}
    <div id="app">
         <span v-bind:title="message">
            鼠标悬停几秒钟查看此处动态绑定的提示信息！
          </span>
        <ol>
            <li v-for="todo in todos">
                <span v-bind:title="todo.text">{{ todo.text }}</span>
            </li>
        </ol>
        <myitem v-for="book in books" v-bind:item="book" v-bind:key="book.id">

        </myitem>
        <button v-on:click="reverseMessage">Reverse</button>
    </div>
    {% endverbatim %}

    <script>
        Vue.component('myitem', {
            props: ['item'],
            template: '<li>{{ item.text }}</li>{{ item.text }}'
        })
        var app = new Vue({
            el: '#app',
            data: {
                message: 'Hello Vue!',
                todos: [
                    {text: '学习 JavaScript'},
                    {text: '学习 Vue'},
                    {text: '整个牛项目'}
                ],
                books: [
                    {id: 1, title: '学习 JavaScript'},
                    {id: 2, title: '学习 Vue'},
                    {id: 3, title: ' 整个牛项目'},
                ]
            },
            methods: {
                reverseMessage: function () {
                    this.message = this.message.split('').reverse().join('')
                }
            }
        })
    </script>

{% endblock content %}

cms/templates/h5videoplayer.html
<html>
<head>
    <meta name="viewport" content="width=device-width">
    <script src="./DataItem.js"></script>
</head>

<body>

<div style="position:relative;left:10%;top:10%">

    <div id="divCanvas"
         style="position:absolute;left:0;top:0;z-index: 10;width: 1280px;height: 720px;">
        <div style="position:relative;left:40%;top:40%">
            <h2>Loading</h2>
        </div>
    </div>

    <div style="position:absolute;top:0;left:0; ">
        <video id="videoplayer1" autoplay
               style="position:absolute;top:0;left:0; width: 1280px;height: 720px;z-index: 1 ">

          <!--<source src="test1.mp4" type="video/mp4">-->
        </video>

        <video id="videoplayer2" autoplay
               style="position:absolute;top:0;left:0; width: 1280px;height: 720px;z-index: 0 ">
                <!--<source src="test1.mp4" type="video/mp4">-->
        </video>
    </div>

</div>

<script>
    'use strict';
    //    const WS_VIDEO_SERVER = 'ws://172.16.16.88:4559';
    const WS_VIDEO_SERVER = 'ws://127.0.0.1:8080';
    const VIDEO_FRAME_RATE = 25;
    const RENDER_INTERVAL = 20;
    const MAX_FRAME_NUM = 100;

    var drawDataDict = new Dictionary();
    var videoPlayer1 = document.getElementById("videoplayer1");
    var videoPlayer2 = document.getElementById("videoplayer2");
    var drawDiv = document.getElementById("divCanvas");

    function addVideoPlayerEvent(videoPlayer, ev, func) {
        videoPlayer.addEventListener(ev, func, false);
    }

    function scaleXByVideo(videoPlayer, x) {
        var result = 0;
        if (!videoPlayer || videoPlayer.videoWidth == 0) {
            return result;
        }
        result = x / videoPlayer.videoWidth * videoPlayer.clientWidth;
        return result;
    }

    function scaleYByVideo(videoPlayer, y) {
        var result = 0;
        if (!videoPlayer || videoPlayer.videoHeight == 0) {
            return result;
        }
        result = y / videoPlayer.videoHeight * videoPlayer.clientHeight;
        return result;
    }

    var removeAllDrawObjects = function () {
        // $("#divCanvas").empty();
        while (drawDiv.childNodes.length > 0) {
            drawDiv.removeChild(drawDiv.firstChild);
        }
    }

    addVideoPlayerEvent(videoPlayer1, "canplaythrough", removeAllDrawObjects);
    addVideoPlayerEvent(videoPlayer2, "canplaythrough", removeAllDrawObjects);

    function threadSleep(sleepDuration) {
        var now = new Date().getTime();
        while (new Date().getTime() < now + sleepDuration) { /* do nothing */
        }
    }

    function getMaxTextLen(rectObj, ctx) {
        var result = 0;
        if (!(rectObj && ctx)) {
            result = 50;
            return result;
        }

        for (var index in rectObj.descs) {
            var item = rectObj.descs[index];
            var width = ctx.measureText(item.descvalue).width;
            if (width > result) {
                result = width;
            }
        }
        return result;
    }

    function getCurrentVideoPlayer() {
        var player = videoPlayer1.style.zIndex == 1 ? videoPlayer1 : videoPlayer2;
        return player;
    }

    function getCurrentFrameNum() {
        var num = Math.floor(getCurrentVideoPlayer().currentTime.toFixed(3) * VIDEO_FRAME_RATE).toFixed(0);
        return num;
    }

    function drawByFrame(frameNum) {
        var result = false;
        var player = getCurrentVideoPlayer();
        console.log("current Frame:%s, player:%s, drawDataDict.len:%s", frameNum, player.id, drawDataDict.size());
        var frameItem = drawDataDict.get(frameNum);
        if (frameItem == undefined) {
            return result;
        }

        removeAllDrawObjects();
        var lineWidth = 2;
        for (var index in frameItem.objects) {
            var item = frameItem.objects[index];
            var canvas = document.createElement("canvas");
            var ctx = canvas.getContext("2d");
            var rectWidth = scaleXByVideo(player, item.width);
            var rectHeight = scaleYByVideo(player, item.height);
            if (rectWidth == 0 || rectHeight == 0) {
                continue;
            }
            var maxTexLen = getMaxTextLen(item, ctx) + 10;//10 for padding
            canvas.width = rectWidth + maxTexLen;
            canvas.height = rectHeight;
            canvas.style.left = scaleXByVideo(player, item.x);
            canvas.style.top = scaleYByVideo(player, item.y);
            canvas.style.position = "absolute";
            drawDiv.appendChild(canvas);
//            $('#divCanvas').append(canvas);
//            console.log("++++ add canvas left:%s , top:%s , width:%s, height:%s , current time:%s,obj_id:%s",
//                canvas.style.left, canvas.style.top, canvas.width, canvas.height, second, item.objid);

            ctx.strokeStyle = item.drawcolor;
            ctx.lineWidth = lineWidth;
            //边框被切问题
            //https://stackoverflow.com/questions/10003468/html5-canvas-and-strokerect-lines-narrower
            ctx.strokeRect(1, 1, rectWidth - 2, rectHeight - 2);

            var txtStartX = rectWidth + 10, txtStartY = 10;
            var fontSize = 10;
            for (var index in item.descs) {
                var desc = item.descs[index];
                ctx.fillStyle = "gray";
                ctx.fillRect(txtStartX, txtStartY - 10, maxTexLen, parseInt(fontSize, 10) + 3);
                ctx.fillStyle = item.drawcolor;
//                            ctx.fillStyle = "white";
                ctx.fontSize = fontSize;
                ctx.fillText(desc.descvalue, txtStartX, txtStartY);
                txtStartY += 20;
            }
            result = true;
        }
        return result;
    }

    function parseData(data) {
        console.log(data);
        var layerData = data.overlays;
        if (!(data && layerData)) {
            return;
        }
        ;
        drawDataDict.clear();
        for (var index in layerData) {
            var item = layerData[index];
            drawDataDict.put(item.frame, new FrameItem(item));
        }
    }

    //structure video stream
    function start_ws_video(url) {
        var wsVideo = new WebSocket(url);
        wsVideo.onopen = function (evt) {
            console.log("video stream web socket connected succeed");
            wsVideo.send("startvideo=rtsp://172.16.16.88:4558/vs/rp/CE:1B:45:CB:45:0E/1/1/");
        };

        wsVideo.onerror = function (evt) {
            console.log("video stream web socket connected failed" + evt.type);
        };
        wsVideo.onmessage = function (evt) {
            var data = JSON.parse(evt.data);
            if (!data || data.code != 200 || data.filename == '' || data.filename == null) {
                console.log("Get video url failed:%s", evt.data);
                return;
            }

            if (videoPlayer1.src == "") {
                videoPlayer1.src = data.filename;
                return;
            }
            //用于让server能有数据返回，正式对接
            //去除以下代码
//            if (wsdata.readyState == WebSocket.OPEN) {
//                wsdata.send(JSON.stringify({my: 'data'}));
//            }
            parseData(data);
            if (!videoPlayer1.paused) {
                videoPlayer2.src = data.filename;
                videoPlayer2.style.zIndex = 1;
                videoPlayer1.style.zIndex = 0;
            } else {
                videoPlayer1.src = data.filename;
                videoPlayer1.style.zIndex = 1;
                videoPlayer2.style.zIndex = 0;
            }
        }
    }

    //    var wsdata = start_ws_data(WS_DATA_SERVER);
    start_ws_video(WS_VIDEO_SERVER);

    setInterval(function () {
        var currentFrame = getCurrentFrameNum();
        var startDate = new Date();
        if (drawByFrame(currentFrame)) {
            var endDate = new Date();
            console.log("drawByFrame invoked elapsed:%s MS", endDate - startDate);
        }

    }, RENDER_INTERVAL);

</script>

</body>
</html>